name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # dispara o deploy quando houver push na main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs mkdocs-material

      - name: Fazer deploy do MkDocs
        run: |
          mkdocs gh-deploy --force
