name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "main" ]   # ajuste se sua branch padrão for outra
  workflow_dispatch:

permissions:
  contents: write   # necessário para push no gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build (sanity check)
        run: mkdocs build --strict

      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --remote-name origin
